name: 'Commitlint'
description: 'Lint commits according to conventional commits specification + YouTrack issue number.'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
    - name: Install commitlint
      shell: bash
      run: |
        npm install commitlint@latest @commitlint/config-conventional

    - name: Validate current commit (last commit) with commitlint
      shell: bash
      if: github.event_name == 'push'
      run: npx commitlint --last --verbose

    - name: Validate PR commits with commitlint
      shell: bash
      if: github.event_name == 'pull_request'
      run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
